import { Idea } from "./db";

export const SEED_IDEAS: Idea[] = [
  {
    id: "seed-1",
    title: "Orbital Carbon Collector",
    domain: "CleanTech",
    problem: "Atmospheric CO2 levels are hitting critical mass, and ground-based DAC (Direct Air Capture) takes too much land.",
    solution: "Low Earth Orbit satellites equipped with advanced aerogel nets that solidify CO2 from the upper atmosphere and drop it safely as stable blocks.",
    whyNow: "Space launch costs are at an all-time low thanks to reusable rockets.",
    submittedBy: "Nova",
    submittedAt: new Date(Date.now() - 86400000).toISOString(),
    implementationScore: 12,
    scoreDetails: "Some academic papers theorize this, but 0 active companies exist. High capital requirement.",
    approved: true,
  },
  {
    id: "seed-2",
    title: "Neuro-Latency Gaming Router",
    domain: "Tech",
    problem: "Pro gamers still suffer from physical network latency beyond their hardware's rendering speed.",
    solution: "A router that uses speculative AI to predict player movements 50ms into the future, pre-fetching the game-state server packets before they happen.",
    whyNow: "On-device AI chips are fast enough to run latency-prediction models in real-time.",
    submittedBy: "Pingmaster",
    submittedAt: new Date(Date.now() - 150000000).toISOString(),
    implementationScore: 45,
    scoreDetails: "2 early-stage startups attempting speculative packet fetching. Still highly experimental.",
    approved: true,
  },
  {
    id: "seed-3",
    title: "Lab-Grown Rare Earth Metals",
    domain: "CleanTech",
    problem: "Mining lithium and cobalt is destroying ecosystems and relying on unstable supply chains.",
    solution: "Using synthetic biology and engineered bacteria to precisely assemble and crystallize rare earth elements from abundant seawater.",
    whyNow: "CRISPR and synthetic biology have reached commercial viability scales.",
    submittedBy: "EcoSynthesizer",
    submittedAt: new Date(Date.now() - 300000000).toISOString(),
    implementationScore: 28,
    scoreDetails: "Research stage. A few university spin-offs are looking into bio-mining, but no commercial synth-metals yet.",
    approved: true,
  },
  {
    id: "seed-4",
    title: "Dream-State Language Learning",
    domain: "EdTech",
    problem: "Learning a language takes years of active, conscious time that adults don't have.",
    solution: "An EEG headband that plays specific targeted vocabulary frequencies during REM sleep specifically timed to memory consolidation spikes.",
    whyNow: "Consumer EEG devices (like Muse) are cheap, and sleep-state memory research is firmly validated.",
    submittedBy: "PolyglotSleep",
    submittedAt: new Date(Date.now() - 500000000).toISOString(),
    implementationScore: 65,
    scoreDetails: "Multiple sleep-audio apps exist, plus a few hardware startups explicitly targeting hypnopaedia.",
    approved: true,
  },
  {
    id: "seed-5",
    title: "Micro-Gravity Manufacturing Lab",
    domain: "SpaceTech",
    problem: "Certain fiber optics and pharmaceuticals cannot be perfectly crystalized on Earth due to gravity causing defects.",
    solution: "An automated autonomous drop-pod factory that orbits for 3 months, grows perfect crystals, and re-enters the atmosphere for recovery.",
    whyNow: "Commercial space stations and re-entry vehicles are becoming private sector standards.",
    submittedBy: "AstroForge Fan",
    submittedAt: new Date(Date.now() - 800000000).toISOString(),
    implementationScore: 82,
    scoreDetails: "Varda Space Industries is already doing exactly this and recently received FDA and FAA approval. High saturation.",
    approved: true,
  },
  {
    id: "seed-6",
    title: "Quantum Encryption for Pacemakers",
    domain: "HealthTech",
    problem: "Medical implants are vulnerable to wireless hacking, which could be fully weaponized.",
    solution: "A bio-compatible hardware module for pacemakers that uses quantum-entangled keys to prevent any external wireless signal from overriding it.",
    whyNow: "Quantum cryptography hardware has finally been miniaturized to the millimeter scale.",
    submittedBy: "ZeroTrust Bio",
    submittedAt: new Date(Date.now() - 1000000000).toISOString(),
    implementationScore: 19,
    scoreDetails: "Zero commercial players. Some cyber-security firms warn about this, but quantum implants are untouched territory.",
    approved: true,
  },
  {
    id: "seed-7",
    title: "AI-Generated Legal Loopholes",
    domain: "FinTech",
    problem: "Major corporations pay millions to lawyers to find tax loopholes. Small businesses can't afford this.",
    solution: "An LLM trained exclusively on the IRS tax code and historical court rulings to automatically structure small business finances for maximum legally-gray deduction.",
    whyNow: "Context windows of LLMs are now large enough to ingest entire tax codes at once.",
    submittedBy: "TaxGPT",
    submittedAt: new Date(Date.now() - 1200000000).toISOString(),
    implementationScore: 75,
    scoreDetails: "Many AI tax assistants exist (Harvey AI, TurboTax AI integration). Finding aggressive loopholes specifically is highly regulated but pursued.",
    approved: true,
  },
  {
    id: "seed-8",
    title: "Synthetic Meat Vending Machines",
    domain: "FoodTech",
    problem: "Lab-grown meat is too expensive to ship frozen and relies on centralized gigafactories.",
    solution: "A localized vending-machine sized bioreactor for restaurants that takes nutrient powder and prints/grows chicken nuggets on-site overnight.",
    whyNow: "Desktop bioreactors and 3D food printing have passed proof-of-concept.",
    submittedBy: "LocalProtein",
    submittedAt: new Date(Date.now() - 1500000000).toISOString(),
    implementationScore: 40,
    scoreDetails: "3D printed meat exists (Redefine Meat), but localized restaurant bioreactors are still highly theoretical due to sterile requirements.",
    approved: true,
  }
];
